### ISSUE TITLE
Media files are not displayed correctly.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#353] opened 2018-12-18 15:01 UTC
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v.2.x, Java vx.x.x, ...

#### Problem description
Media: Images, Videos, Audio, even Audit miniatures are not displayed correctly.
There is no way to open Images, Video and Audio.
Audit file is opening correctly.

#### Steps to reproduce the problem
Just open submissions view for form with media files.

#### Expected behavior
Miniatures should be visible.
The user should be able to open media and view them.

#### Other information 
Screenshot of the current behavior:
![screenshot from 2018-12-18 15-50-55](https://user-images.githubusercontent.com/33342488/50162227-19c75580-02de-11e9-82f4-a165d99cd3a4.png)

**Comment by ggalmazor** [comment] 2018-12-20 10:19
Can't reproduce, and now I'm using your database :)

![image](https://user-images.githubusercontent.com/205913/50279075-0a185000-0449-11e9-88bd-f2e33a8478bb.png)

**Comment by kkrawczyk123** [comment] 2018-12-27 08:04
@ggalmazor, on the newest master I am not able to reproduce as well. All media files displays and I am able to open them.

**Comment by ggalmazor** [comment] 2018-12-27 08:13
Then, shall we close this issue?

**Comment by kkrawczyk123** [comment] 2018-12-27 08:17
Yeah, let's treat it as an Xmas miracle xd

**Closed** 2018-12-27 08:40 UTC
