### ISSUE TITLE
ODK Aggregate Windows 1.7.1 not downloading in full.

### ISSUE THREAD

**Issue by kirkglynch** [opendatakit/aggregate#394] opened 2019-01-29 12:35 UTC
#### Software and hardware versions 
Windows

#### Problem description
Good afternoon. I'm unsure if the fault is on my end but I am unable to get a complete download of the zip file for the windows installer. Is it possible to confirm the file is downloadable so I may investigate my side further.
Thanks

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by kirkglynch** [comment] 2019-01-29 12:37
Good afternoon. I'm unsure if the fault is on me end but I am unable to get a complete download of the zip file for the windows installer. Is it possible to confirm the file is downloadable so I may investigate my side further.
Thanks

**Comment by ggalmazor** [comment] 2019-01-29 12:40
Thanks for reporting this, @kirkglynch. I'll check it and get back to you.

**Comment by ggalmazor** [comment] 2019-01-29 12:44
Verified: I can download, unzip and run the Windows installer.

**Comment by ggalmazor** [comment] 2019-01-29 12:45
Just in case, this is the link I'm using (from the official releases page): https://github.com/opendatakit/aggregate/releases/download/v1.7.1/ODK-Aggregate-v1.7.1-Windows.exe.zip

**Comment by kirkglynch** [comment] 2019-01-29 12:58
Thanks @ggalmazor. I'll try again. It runs to complete the download but I can see the zip file is light in size...

**Comment by ggalmazor** [comment] 2019-01-29 15:23
Cool.

I'm going to close this issue since I've been unable to reproduce it, but feel free to reopen it if you find out anything new.

**Closed by ggalmazor** 2019-01-29 15:23 UTC
